### ISSUE TITLE
Realtek Audio Console shows wrong driver version

### ISSUE THREAD

**Issue by hamburml** [AlanFinotty/AAFDCHDriverMod#118]
HI there,

I have a Gigabyte x570 AORUS Pro. I installed AAFAudioPackDCH-6.0.9172.1 and choose only the realtek audio console and the decoder. After installation the audio console shows "6.0.9075.1" as driver instead of 9172.1.

Any ideas what I did wrong or missed?

Thx!

**Comment by AlanFinotty** [comment]
Uninstall it, use DriverStoreExplorer to remove any and all residue from previous drivers, then install the mod again. There may be some residue left before you even installed the package.

**Comment by hamburml** [comment]
Thanks for the response. I removed everything and installed the mod again. Now the realtek audio console shows an error "Cannot connect to RPC service" :(
I have win10 2141 (19043.1055)

**Comment by hamburml** [comment]
I tried 6.0.9160.1 and now it's working.

I think the following is strange...
![image](https://user-images.githubusercontent.com/7239350/121807969-b3c1ac00-cc56-11eb-99d6-237ca456a36b.png)
It shows the "AAF Optimus Universal Sound" under 'Unbekannt' which is german for 'unknown'.
