### ISSUE TITLE
cannot installing T^T

### ISSUE THREAD

**Issue by Meikiv** [AlanFinotty/AAFDCHDriverMod#127]
![image](https://user-images.githubusercontent.com/84654332/125364564-b1fe1c00-e3ad-11eb-860c-c6a919852f27.png)
Attempting to install the driver results in the above error.
I removed the driver from Device Manager and deleted all Realtek drivers from Driver Store Explorer, but it still doesn't work.

I'm not good at English, but I hope it's delivered.

**Comment by AlanFinotty** [comment]
Open CMD and execute:
`reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{F132AF7F-7BCA-4EDE-8A7C-958108FE7DBD}_is1 /f`

and retry

**Comment by Meikiv** [comment]
It works perfectly!
thx!! :D
