### ISSUE TITLE
Realtek Audio Console never completely loads

### ISSUE THREAD

**Issue by AlienXAXS** [AlanFinotty/AAFDCHDriverMod#140]
Hi,
I have installed this audio driver for my ASUS Maximus XI Forumula board, the driver itself seems to be working as intended, Sonic Studio also seems to be working too which is good.

However, the Realtek Audio Console loads, and just shows the spinning loading dots and nothing else.

Is there a fix for this? - I want to enable DDL.

**Comment by epman100** [comment]
what version of the DCH modded audio driver did you install?
