### ISSUE TITLE
Lightweight installer without enhancements suggestion; fix combo jack audio.

### ISSUE THREAD

**Issue by riposte01** [AlanFinotty/AAFDCHDriverMod#153]
Hi AlanFinotty,
I wonder if you willing to release lightweight installer without additional components, so purely DCH Realtek Audio Driver.
Right now I'm using Apr 02, 2021, 6.0.9132.1 version because it's the smallest (180MB) and the most recent installer.
I'm using Dell Latitude 7490. OEM Realtek driver is big (600MB), legacy (HDA), and bloated because of Waves MaxxAudio which is not useful for me.
And I hope you able to fix combojack, most users need this.

The reason I'm not using pal1000 driver because there is a bug that affects hardware. Every time playing audio, there is a sudden unpleasant audio popup. It does support combojack headset btw.

Thanks for your effort creating this AAFDCH driver.

**Comment by AlanFinotty** [comment]
Package avaivable in most recent version (OnlyRTK)
