### ISSUE TITLE
Could you update DAX API Service to 3.30202.224.0?

### ISSUE THREAD

**Issue by brainos233** [AlanFinotty/AAFDCHDriverMod#162]
I installed the latest release and noticed that the version of dax3_swc_aposvc was too old. It may caused some problems  when using Dolby Atmos for Gaming, like crushing randomly. Using the newest version can make it worked more stable

**Comment by AlanFinotty** [comment]
I did tests with the latest version (3.30203.232.0) and unfortunately the Dolby Atmos application was not functional. For this reason, I keep the previous version (3.20900.911.0).
