### ISSUE TITLE
5.1 Speakers not working - ALC892

### ISSUE THREAD

**Issue by mithun25m** [AlanFinotty/AAFDCHDriverMod#32]
Hi Alan,
Thank you for your modded drivers. This helps my pc sound to the next level. But in the latest release (AAF DCH Optimus Sound 6.0.9008.1 (Signed)) 5.1 speakers are not working. It is working as a stereo sound. Till version AAF DCH Optimus Sound 6.0.9003.1 (Signed) it was working fine.  I have an ALC892 audio chipset in the DH67BL motherboard. I hope you will look into this and fix this issue.

**Comment by mithun25m** [comment]
I have tried your newer version - AAF DCH Optimus Sound 6.0.9013.1 (Signed) released today. This also has the same issue. As I said above I am using ALC892 audio chipset in the DH67BL motherboard and connecting through SPDIF Optical output. Can you please look into this and advise.

**Comment by BillTaozi** [comment]
![sshot-1](https://user-images.githubusercontent.com/35515198/93011858-df7f0b00-f5cc-11ea-8727-94305e2c8e15.png)
![sshot-3](https://user-images.githubusercontent.com/35515198/93011869-faea1600-f5cc-11ea-9858-24e82045f8f5.png)
我正在使用您的较新版本-今天发布的AAF DCH Optimus Sound 6.0.9013.1（签名）。这也有同样的问题，我的主板100 声卡 ALC0298          HDAUDIO\FUNC_01&VEN_10EC&DEV_0298&SUBSYS_102807BE&REV_1001\4&1E3FD26D&8&0001

**Comment by mithun25m** [comment]
Hi Alan,

I am still facing the same issue in your latest driver (DCH DRIVER VERSION 6.0.9018.1) too. There is option Dolby Digital Live in sound properties and it is selected. But when I play the 5.1 surround sound file like dolby atmos trailer, the sound is stereo instead of 5.1. This issued was not faced till version 9003.1. Can you help me to fix this please.

**Comment by mithun25m** [comment]
Along with above mentioned I have a suggestion. The standard version (ver: 8960) works very well compared to DCH version because equalizer in Sonic studio and Dolby Atmos are not working in DCH version. May be it's my hardware compatibility problem. Can you update the latest version of creative SB connect, Sonic studio and Dolby atmos to the standard version drivers if possible.

**Comment by ivicask** [comment]
Same issue, ALC1150 , connected over optical to my soundbar, Dolby live 5.1, With Dolby Home Theater option i dont get sound on back speakers, even with old version 8960, tried both DCH and legacy. When i install some random Realtek High Definition Audio 6.0.8924.1.WHQL_ASIO_DTS_DOLBY-unlock driver form net all above metnion works fine and i get sound on all speakers and upxming of stereo sources works also.

**Comment by jhortwo** [comment]
Hi, anyone solved the back speakers problem with the ALC892?

**Comment by mithun25m** [comment]
Hi Alan,

I have upgraded my system and current audio driver is ALC897. When i installed your latest DCH driver (V 9231.1), the surround speakers are not working. So i found a driver in your thread posted recently - AAFOptimusAudioPackXFi9209 which works fine for surround speakers. So I took the realtek drivers from this and updated in the AAFOptimusAudioPack9209 driver. Now all the APO's are working fine with surround effect (5.1). So could you please use this type of driver for your future drivers so that 5.1 surround won't be a problem.
