### ISSUE TITLE
The THX truestudio PRO is not working

### ISSUE THREAD

**Issue by RCCore** [AlanFinotty/AAFDCHDriverMod#42]
![image](https://user-images.githubusercontent.com/63298991/95317153-71f98e00-089d-11eb-902d-28bd0eb5ee12.png)

**Comment by epman100** [comment]
check if the ctlt99hb0x.kga license file is in the C:\ProgramData\Creative\SoftwareLock folder.
THX Trustudio Pro requires that specific kga file to be there in order for it to recognize the onboard Realtek audio device

**Comment by RCCore** [comment]
But I don't have that file so how do I get the file...

**Comment by epman100** [comment]
[https://www.techpowerup.com/forums/threads/realtek-dch-modded-audio-driver-for-windows-10.250915/](https://www.techpowerup.com/forums/threads/realtek-dch-modded-audio-driver-for-windows-10.250915/)

download KGA config tool to generate a valid **ctlt99hb0x.kga** file and remove all other KGA files

**Comment by RCCore** [comment]
Thanks for the response but I will remain with the Sound Blaster Cinema 5.

**Comment by epman100** [comment]
though SBCinema5 uses a different kga license file

but the THX Trustudio Pro problem should be resolved with the recent modded [9066 driver re-release (w/ Nahimic fix)](https://github.com/AlanFinotty/AAFDCHDriverMod/releases/tag/6.0.9066.2) as I tested this version on my HP computer and THX Trustudio Pro is working

**Comment by RCCore** [comment]
@epman100 Thanks for helping me out.
