### ISSUE TITLE
No audio in pot player and dolby not installing.

### ISSUE THREAD

**Issue by Sumit75667** [AlanFinotty/AAFDCHDriverMod#57]
installed - realtek universal both decoder, nahimic, dolby atom, realtek tweak

pot player no-sound happening frequently with/without LAV. always when changing audio in dual audio movies, frequently when playing a file.

Dolby installed properly on first install. not installing afterward when I uninstall-restart-install-restart. tried multiple time.

running newest windows.

**Comment by Sumit75667** [comment]
Identified 
potplayer issue: Directsound output bugged, waveout works fine.
Dolby: Installer need repairing.

**Comment by AlanFinotty** [comment]
> Identified
> potplayer issue: Directsound output bugged, waveout works fine.
> Dolby: Installer need repairing.

Bug already fixed.
