### ISSUE TITLE
When I uninstall the driver in Windows Update it remains Exclude Drivers from Windows quality updates message!

### ISSUE THREAD

**Issue by RCCore** [AlanFinotty/AAFDCHDriverMod#58]
How to fix this?

**Comment by AlanFinotty** [comment]
Open CMD, paste these commands and press ENTER:
**reg delete HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate /v ExcludeWUDriversInQualityUpdate /f**
**reg delete HKLM\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings /v ExcludeWUDriversInQualityUpdate /f**

**Comment by RCCore** [comment]
@AlanFinotty Thank You so much, and good luck on your project its so good.
