### ISSUE TITLE
[ALC261] Multi channel sound not working anymore

### ISSUE THREAD

**Issue by BennoMP** [AlanFinotty/AAFDCHDriverMod#60]
In version 9066.1, I could use quadrophonic, 5.1 and 7.1 channel sound on my ALC261 but on any version above that or below that I can't. It reported as a different chip model too (ALC662 if I recall correctly), but that was not an issue. I pulled up a datasheet of both and they have similar functions, functions like multi channel sound seem to be disabled in the driver itself. It could also be because of the changes made in 9071.1 but I'm not sure about it. There was also a function that enabled optimizations for certain usecases (music and movie) which is gone now.
I hope this is not a driver thing but something I can change in the Realtek Device Tweak tool.

**Comment by AlanFinotty** [comment]
Realtek itself makes periodic changes to the driver kernel. In that case, I cannot intervene.

**Comment by BennoMP** [comment]
So I'll just have to stay on that driver and check every once in a while if it's on a new driver?
