### ISSUE TITLE
How do i install this mod?

### ISSUE THREAD

**Issue by CAPTAIN-KENWAY** [AlanFinotty/AAFDCHDriverMod#67]
I can't seem to find anywhere the installation guide. Please help me. I am new to this mod. What are the prerequisites needed for this mod and how to use this mod. Thanks

**Comment by RCCore** [comment]
Just Uninstall your Realtek driver and Launch the executable and Install it (If you want the best option then select Realtek Universal with both decoders , Dolby Atmos, Creative Sound Blaster Cinema 5 and Sonic Studio 3, If you want to chose Nahimic you may encounter bugs) and thats it.

**Comment by CAPTAIN-KENWAY** [comment]
I didn't uninstall the Realtek drivers just installed it. Sound blaster and Realtek audio console were not showing anything.

**Comment by RCCore** [comment]
> 
> 
> I didn't uninstall the Realtek drivers just installed it. Sound blaster and Realtek audio console were not showing anything.

You need to uninstall The Realtek Drivers and the AFF Driver now, and just install the AFF Driver.

**Comment by CAPTAIN-KENWAY** [comment]
> > I didn't uninstall the Realtek drivers just installed it. Sound blaster and Realtek audio console were not showing anything.
> 
> You need to uninstall The Realtek Drivers and the AFF Driver now, and just install the AFF Driver.

I did...it worked...thanks
