### ISSUE TITLE
Driver doesn't work on Msi B550 Gaming Plus.

### ISSUE THREAD

**Issue by the4anoni** [AlanFinotty/AAFDCHDriverMod#68]
Hello like in topic.
I removed previous Realtek Driver via Unistall Programs, and after this I ran DDU in Safe mode to clean up old realtek driver.

After installing this driver Realtek Control Center (UWP Version) loads endlessly, Creative software also doesn't work (even after running KGAConfig).

This motherboard has ALC 892, driver from Msi works without any problem.

I've tried AAF DCH Optimus Sound 6.0.9091.1 (UPDATE) (Signed).

**Comment by RCCore** [comment]
AAF DCH Optimus Sound 6.0.9091.1 (UPDATE) (Signed) this version its buggy , I reccomend to install the other version without the (UPDATE).

**Comment by the4anoni** [comment]
Also I've noticed that uninstalling that's driver didn't removed THX.

**Comment by RCCore** [comment]
Just install the another version and wait. (I hope the problem will be resolved)

**Comment by the4anoni** [comment]
Older version works ok, but how can I block nahimic from updating?

**Comment by RCCore** [comment]
> 
> 
> Older version works ok, but how can I block nahimic from updating?
> 
> Never mind, got it.

I reccomend to install Sonic Studio 3 because for me its better than Nahimic.

**Comment by RCCore** [comment]
The problems have been fixed now you can upgrade to the latest version.

**Comment by the4anoni** [comment]
Installed them just now, all works fine for now.

**Comment by the4anoni** [comment]
@RCCore do you know difference between  Sound Blaster 360, 720 and Cinema 5?

**Comment by RCCore** [comment]
> @RCCore do you know difference between  Sound Blaster 360, 720 and Cinema 5?
Yes I know the difference

**Comment by RCCore** [comment]
I will respond later.

**Comment by RCCore** [comment]
> 
> 
> @RCCore do you know difference between Sound Blaster 360, 720 and Cinema 5?
Its not a difference between them 360 and 720 offers vocal changer, and Sound Cinema 5 offers a new Audio Engine. (So not much of a difference)
