### ISSUE TITLE
[Feature Request] VIA HD Audio support?

### ISSUE THREAD

**Issue by Hexality** [AlanFinotty/AAFDCHDriverMod#72]
Hi, asking for a friend: Can you make a way to support VIA HD Audio? He's driver is getting too old and he wanted to get some better driver to also get a better quality. I would appreciate if possible.

**Comment by AlanFinotty** [comment]
Oi, vi que também é brasileiro.
Bom, infelizmente não é possível fazê-lo pelo fato de eu não ter uma plataforma compatível para testes. Desde já me desculpo.
Eu poderia até fazer, mas a tentativa seria às cegas, sem nenhuma possibilidade de testar o possível mod antes de divulgá-lo.
Mil desculpas,
Alan.

**Comment by Hexality** [comment]
Sem problemas, agradeço mesmo assim. o7

**Comment by gustavo-vasquez** [comment]
Hi, this mod is compatible with Realtek ALC1200 codec?

**Comment by AlanFinotty** [comment]
> Hi, this mod is compatible with Realtek ALC1200 codec?

YES

**Comment by gustavo-vasquez** [comment]
> > Hi, this mod is compatible with Realtek ALC1200 codec?
> 
> YES

Thank you!

**Comment by epman100** [comment]
> Hi, asking for a friend: Can you make a way to support VIA HD Audio? He's driver is getting too old and he wanted to get some better driver to also get a better quality. I would appreciate if possible.

Alan F recently has made a [separate modded driver pack in TPU forums](https://www.techpowerup.com/forums/threads/aaf-optimus-dch-audio-modded-driver-for-windows-10-11-for-all-hdaudio-enumerator-chips.292621/) that might work on Via hd audio devices

so therefore I think Alan F can now mark this issue as "Closed" and not leave this as an Open issue
