### ISSUE TITLE
Request: support for Conexant SmartAudio HD

### ISSUE THREAD

**Issue by BennoMP** [AlanFinotty/AAFDCHDriverMod#75]
I'd like to see this happen because the stock driver I have has Dolby Digital Plus 2014 and it's a horrible program to use and tune. Volume will also be exceedingly high, even at 10%. Issues I've never had with other sound enhancement tools. I've already looked through the official Conexant driver for my device and it doesn't look too hard to mod, but I'm no pro so I can't really tell.
My sound card has the ID `HDAUDIO\FUNC_01&VEN_14F1&DEV_510F&SUBSYS_17AA3801&REV_1001\4&157DCDAD&0&0001
` if that has any added value. It seems like the last of these chips is from 2016.

**Comment by epman100** [comment]
actually Alan F has recently made a [separate modded driver pack in TPU forums](https://www.techpowerup.com/forums/threads/aaf-optimus-dch-audio-modded-driver-for-windows-10-11-for-all-hdaudio-enumerator-chips.292621/) that might work on your Conexant SmartAudio HD hardware and possibly other Conexant HD audio devices

so therefore I think Alan F can now mark this issue as "Closed" and not leave this as an Open issue
