### ISSUE TITLE
Dolby atmos not installing in the latest version.

### ISSUE THREAD

**Issue by FrannDzs** [AlanFinotty/AAFDCHDriverMod#80]
Hi, I recently installed your audio kit and noticed that dolby atmos is not installed, just select Dolby Atmos in the installation. This problem had already happened to me some time ago in another version but you solved it so it seems that it is again the same problem, greetings!

**Comment by RCCore** [comment]
> 
> 
> Hi, I recently installed your audio kit and noticed that dolby atmos is not installed, just select Dolby Atmos in the installation. This problem had already happened to me some time ago in another version but you solved it so it seems that it is again the same problem, greetings!

You installed the latest version of this driver?

**Comment by FrannDzs** [comment]
> > Hi, I recently installed your audio kit and noticed that dolby atmos is not installed, just select Dolby Atmos in the installation. This problem had already happened to me some time ago in another version but you solved it so it seems that it is again the same problem, greetings!
> 
> You installed the latest version of this driver?

Hi, yes, I had the last version working normally and after this last update Dolby Atmos was not installed, it is a problem that had already happened if you look at the issues table.

**Comment by FrannDzs** [comment]
> > Hi, I recently installed your audio kit and noticed that dolby atmos is not installed, just select Dolby Atmos in the installation. This problem had already happened to me some time ago in another version but you solved it so it seems that it is again the same problem, greetings!
> 
> You installed the latest version of this driver?



> > Hi, I recently installed your audio kit and noticed that dolby atmos is not installed, just select Dolby Atmos in the installation. This problem had already happened to me some time ago in another version but you solved it so it seems that it is again the same problem, greetings!
> 
> You installed the latest version of this driver?

Oh, it was you who opened that problem, then you know what I'm talking about, greetings!

**Comment by AlanFinotty** [comment]
Thanks for the feedback. Problem identified. For those who still do not understand the installation of Dolby Atmos, the package for installing it is attached [**HERE**](https://github.com/AlanFinotty/AAFDCHDriverMod/blob/master/DolbyAtmos.Appx), while working on a solution. Grateful.

**Comment by FrannDzs** [comment]
> Thanks for the feedback. Problem identified. For those who still do not understand the installation of Dolby Atmos, the package for installing it is attached [**HERE**](https://github.com/AlanFinotty/AAFDCHDriverMod/raw/master/DolbyAtmos.Appx) (open link a new tab), while working on a solution. Grateful.

thanks Alan! you are the best!

**Comment by Farhankhosravi** [comment]
> Thanks for the feedback. Problem identified. For those who still do not understand the installation of Dolby Atmos, the package for installing it is attached [**HERE**](https://github.com/AlanFinotty/AAFDCHDriverMod/raw/master/DolbyAtmos.Appx) (open link a new tab), while working on a solution. Grateful.

Hello
i tried this solution... the app installation filed with this error:

App installation failed with error message: Windows cannot install package DolbyLaboratories.DolbyAtmos_3.20900.902.0_x64__rz1tebttyb220 because this package depends on a device driver that could not be found.  One of the following device drivers must be installed: {[Dolby-dax3_swc_hsa.INF, 3.20900.902.0, 2020-06-05], [Dolby-dax3_swc_hsa_arm64.INF, 3.20900.902.0, 2020-06-05]} (0x80073cfd)

what can i do?...

**Comment by Patraskon** [comment]
Most likely, the manually installed Realtek driver interferes

**Comment by Farhankhosravi** [comment]
> Most likely, the manually installed Realtek driver interferes
Sorry, i didn't catch.., do you mean that i installed my drivers manually?

I just deleted all drivers and then installed AAF software... And these problems happened 
(There is no dolby atmos in latest version too)
